CREATE TABLE "MBDWH"."CAL905_CANCELACION" 
   (	"FECHA" DATE, 
	"HORA" NUMBER(6,0), 
	"CODESTACIONDEST" VARCHAR2(3 BYTE), 
	"CODESTACIONORIG" VARCHAR2(3 BYTE), 
	"NUMCANCELACIONES" NUMBER(5,0)
   ) ;

  CREATE INDEX "MBDWH"."IND_CAL905" ON "MBDWH"."CAL905_CANCELACION" ("FECHA", "CODESTACIONORIG", "CODESTACIONDEST") 
  ;