CREATE TABLE "MB"."MBG050_CENTROSMB" 
   (	"CODCENTRO" VARCHAR2(3 BYTE), 
	"DESCENTRO" VARCHAR2(40 BYTE), 
	"NUMCENTRO" NUMBER(4,0), 
	"CODLINEA" NUMBER(1,0), 
	"ZONATARIFARIA" VARCHAR2(1 BYTE), 
	"PUNTOKM" NUMBER(6,3), 
	"ID_ESTACION" VARCHAR2(1 BYTE), 
	"ID_TALLER" VARCHAR2(1 BYTE), 
	"ID_ALMACEN" VARCHAR2(1 BYTE), 
	"ID_OAC" VARCHAR2(1 BYTE), 
	"ID_CENTRAL" VARCHAR2(1 BYTE), 
	"ID_TEMPORAL" VARCHAR2(1 BYTE), 
	"ID_EMPRESACONC" VARCHAR2(1 BYTE), 
	"IDZONASUPLEMENTARIO" VARCHAR2(1 BYTE), 
	"IDMUNICIPIO" VARCHAR2(4 BYTE), 
	"IDDISTRITO_CENSAL" VARCHAR2(10 BYTE), 
	"IDSECCION_CENSAL" VARCHAR2(10 BYTE), 
	"COORD_X" NUMBER, 
	"COORD_Y" NUMBER, 
	"SUBZONATARIFARIA" VARCHAR2(2 BYTE), 
	"ORDENESTACION" NUMBER(4,0), 
	"CUADRO_MARCHA_NCOL" NUMBER, 
	"CUADRO_MARCHA_TCOMUN" NUMBER DEFAULT 0, 
	"CUADRO_MARCHA_ALIAS" VARCHAR2(50 BYTE)
   ) ;

   COMMENT ON COLUMN "MB"."MBG050_CENTROSMB"."IDMUNICIPIO" IS 'Código de municipio';
   COMMENT ON COLUMN "MB"."MBG050_CENTROSMB"."IDDISTRITO_CENSAL" IS 'Distrito censal';
   COMMENT ON COLUMN "MB"."MBG050_CENTROSMB"."IDSECCION_CENSAL" IS 'Sección censal';
   COMMENT ON COLUMN "MB"."MBG050_CENTROSMB"."SUBZONATARIFARIA" IS 'Subzona tarifaria';
   COMMENT ON COLUMN "MB"."MBG050_CENTROSMB"."CUADRO_MARCHA_NCOL" IS 'Columna del informe de cuadro de marcha. Las estaciones de L1 y L2 que tengan el mismo número compartirán la columna. P.e. LUT y GUR, ANS y ERA, ...';
   COMMENT ON COLUMN "MB"."MBG050_CENTROSMB"."CUADRO_MARCHA_TCOMUN" IS 'Indica que la columna en el cuadro de marcha es común';

  CREATE UNIQUE INDEX "MB"."UK1_MBG050_NUMCENTRO" ON "MB"."MBG050_CENTROSMB" ("NUMCENTRO") 
  ;