CREATE TABLE "MBDWH"."OLAPTRF050_CIRCULACIONREAL" 
   (	"FECHASERVICIO" DATE, 
	"FECHACIRCULACION" DATE, 
	"NUMMATERIAL" VARCHAR2(5 BYTE), 
	"NUMSERVICIO" VARCHAR2(3 BYTE), 
	"NUMCIRCULACION" VARCHAR2(5 BYTE), 
	"ESTACIONPARADA" VARCHAR2(3 BYTE), 
	"ANDENPARADA" VARCHAR2(1 BYTE), 
	"HORALLEGADATEOR" NUMBER(6,0), 
	"HORALLEGADAREAL" NUMBER(6,0), 
	"HORASALIDATEOR" NUMBER(6,0), 
	"HORASALIDAREAL" NUMBER(6,0), 
	"KILOMETROS" VARCHAR2(8 BYTE), 
	"TIPOCIRCULACION" VARCHAR2(1 BYTE) DEFAULT ('T'), 
	"PASAJEROS" NUMBER(1,0) DEFAULT (-1), 
	"NUMEROCOCHES" NUMBER(1,0), 
	"LINEA" NUMBER(2,0), 
	"SENTIDO" NUMBER(1,0), 
	"IDINSTALACION" CHAR(3 BYTE), 
	"IDSERIE" CHAR(3 BYTE), 
	"IDUNIDAD" CHAR(4 BYTE), 
	"VELOCIDAD" VARCHAR2(1 BYTE), 
	"CIRCID" NUMBER
   )  ENABLE ROW MOVEMENT ;

   COMMENT ON COLUMN "MBDWH"."OLAPTRF050_CIRCULACIONREAL"."NUMEROCOCHES" IS 'Numero de vagones de la unidad (nummaterial)';
   COMMENT ON COLUMN "MBDWH"."OLAPTRF050_CIRCULACIONREAL"."LINEA" IS 'Linea 1,2';
   COMMENT ON COLUMN "MBDWH"."OLAPTRF050_CIRCULACIONREAL"."SENTIDO" IS 'Sentido de la circulacion';
   COMMENT ON COLUMN "MBDWH"."OLAPTRF050_CIRCULACIONREAL"."IDINSTALACION" IS 'De la unidad que esta haciendo la circulacion.';
   COMMENT ON COLUMN "MBDWH"."OLAPTRF050_CIRCULACIONREAL"."IDSERIE" IS 'De la unidad que esta haciendo la circulacion.';
   COMMENT ON COLUMN "MBDWH"."OLAPTRF050_CIRCULACIONREAL"."IDUNIDAD" IS 'Que esta haciendo la circulacion.';

  CREATE INDEX "MBDWH"."IND_OLAPTRF050" ON "MBDWH"."OLAPTRF050_CIRCULACIONREAL" ("FECHACIRCULACION", "ESTACIONPARADA", "PASAJEROS") 
  ;