CREATE TABLE "MBDWH"."CAL200_CARGATRENES" 
   (	"FECHA" DATE, 
	"NUMSERVICIO" VARCHAR2(3 BYTE), 
	"NUMCIRCULACION" VARCHAR2(5 BYTE), 
	"CODESTACIONORIGEN" VARCHAR2(3 BYTE), 
	"CODESTACIONDESTINO" VARCHAR2(3 BYTE), 
	"HORASALIDA" NUMBER(6,0), 
	"HORALLEGADA" NUMBER(6,0), 
	"CARGA" NUMBER(5,0), 
	"HORASALIDATEORICA" NUMBER(6,0), 
	"HORALLEGADATEORICA" NUMBER(6,0), 
	"NUMMATERIAL" VARCHAR2(5 BYTE), 
	"NUMEROCOCHES" NUMBER(1,0) DEFAULT 0, 
	"LINEA" NUMBER(1,0), 
	"SENTIDO" NUMBER(1,0)
   )  ENABLE ROW MOVEMENT ;

   COMMENT ON COLUMN "MBDWH"."CAL200_CARGATRENES"."FECHA" IS 'Fecha de la circulacion';
   COMMENT ON COLUMN "MBDWH"."CAL200_CARGATRENES"."NUMSERVICIO" IS 'Numero de servicio';
   COMMENT ON COLUMN "MBDWH"."CAL200_CARGATRENES"."NUMCIRCULACION" IS 'Identificativo de la circulacion';
   COMMENT ON COLUMN "MBDWH"."CAL200_CARGATRENES"."CODESTACIONORIGEN" IS 'Codigo de la estacion de salida';
   COMMENT ON COLUMN "MBDWH"."CAL200_CARGATRENES"."CODESTACIONDESTINO" IS 'Codigo de la estacion de llegada';
   COMMENT ON COLUMN "MBDWH"."CAL200_CARGATRENES"."HORASALIDA" IS 'Hora real de salida en origen';
   COMMENT ON COLUMN "MBDWH"."CAL200_CARGATRENES"."HORALLEGADA" IS 'Hora real de llegada a destino';
   COMMENT ON COLUMN "MBDWH"."CAL200_CARGATRENES"."CARGA" IS 'Personas que han viajado en el tren';
   COMMENT ON COLUMN "MBDWH"."CAL200_CARGATRENES"."HORASALIDATEORICA" IS 'Hora teorica de salida del tren';
   COMMENT ON COLUMN "MBDWH"."CAL200_CARGATRENES"."HORALLEGADATEORICA" IS 'Hora teorica de llegada del tren';
   COMMENT ON TABLE "MBDWH"."CAL200_CARGATRENES"  IS 'Tabla calculada a partir de los datos de trafico. Contiene la informacion de las circulaciones completas de cada dia.';